server:
  build: ./empire
  links:
    - postgres:postgres
  ports:
    - "8080:8080"
  volumes:
    - ~/.dockercfg:/root/.dockercfg
    - .:/go/src/github.com/remind101/empire
  env_file: .env
  user: root
  working_dir: /go/src/github.com/remind101/empire/cmd/empire
  environment:
    EMPIRE_DATABASE_URL: postgres://postgres:postgres@postgres/postgres?sslmode=disable
    DOCKER_HOST:
postgres:
  image: postgres
  ports:
    - "5432:5432"
